name: publish

on:
  push:
    branches:
      - production
      - develop
      - stage
      - test

jobs:
  build-and-publish-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fanavar/admin-panel:${{ github.ref_name }}

  deploy:
    runs-on: self-hosted
    needs: build-and-publish-image
    steps:
      - name: Deploy Docker Image to Server
        run: ~/devops/admin-panel/deploy.sh ${{ github.ref_name }}